version: "3"
volumes:
  db:
services:
  server:
    image: jannchie/gazer-system-server
    build:
      dockerfile: docker/server.dockerfile
      context: .
    ports:
      - "2001:2001"
    volumes:
      - db:/data
    environment:
      TOR: "proxy:9050"
      TOR_CTL: "proxy:9051"
      GSS_PORT: 2001
      DB: "postgres"
      DSN: "postgres://postgres:postgres@db:5432/postgres"
      TOR_PASSWORD: ${TOR_PASSWORD}
      CONCURRENCY: 8
  proxy:
    image: dperson/torproxy
    expose:
      - 9050
      - 9051
    environment:
      PASSWORD: ${TOR_PASSWORD}
  client:
    build:
      dockerfile: docker/test.dockerfile
  db:
    image: postgres
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres