version: "3"
volumes:
  db:
services:
  server:
    image: jannchie/gazer-system-server
    build:
      dockerfile: docker/server.dockerfile
      context: .
    ports:
      - "2000:2000"
    volumes:
      - db:/data
    environment:
      TOR: "proxy:9050"
      TOR_CTL: "proxy:9051"
      PORT: 2000
      DSN: "/data/gazer-system.db"
      TOR_PASSWORD: ${TOR_PASSWORD}
      CONCURRENCY: 8
  proxy:
    image: dperson/torproxy
    expose:
      - 9050
      - 9051
    environment:
      PASSWORD: ${TOR_PASSWORD}
